language: php

php:
  - 7.1
  - 7.2

script:
  - vendor/bin/phpunit

before_script:
  - echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "apc.enable_cli = On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

after_success:
  - bash <(curl -s https://codecov.io/bash)